require("plugins")
require("settings")
require("colorsch")
require("keymaps")
require("dashboard_conf")
require("filetype_conf")
require("mason_nvim_conf")
-- require("nvim_autotag_conf")
require("nvim_autopairs_conf")
require("nvim_surround_conf")
require("treesitter_conf")
require("lsp_conf")
require("luasnip_conf")
require("autocompletion_conf")
require("null_ls")
require("flutter_tools_conf")
require("nvim_tree_conf")
require("feline_conf")
require("trouble_conf")
require("telescope_conf")
require("leap_conf")
-- require("lualine_conf")
require("fzf_conf")
--require("vimtex_conf")
require("floaterm_conf")
require("possession_conf")
require('gitsigns_conf')
require('nvim_notify_conf')
